apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-app2
  namespace: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes-app2
  template:
    metadata:
      labels:
        app: hello-kubernetes-app2
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-second
  namespace: app2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: hello-kubernetes-second
