apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: Hello from the first deployment
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-first
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: hello-kubernetes-first
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: hello-kubernetes
            port:
              number: 80
