apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube-original
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarqube
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    #path: apps/dfp-h-sonarqube-original
    targetRevision: '1.1'
    helm:
      releaseName: sonarqube
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}